name: Build

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - name: Checkout Metamod
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/metamod-source
          ref: master
          path: mmsource-2.0
          submodules: recursive

      - name: Checkout HL2SDK
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/hl2sdk
          ref: cs2
          path: hl2sdk-cs2

      - name: Checkout AMBuild
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        run: |
          cd ambuild && python setup.py install && cd ..

      - name: Build
        working-directory: .
        shell: bash
        run: |
          mkdir build && cd build
          python ../configure.py --enable-optimize --symbol-files --sdks cs2 --hl2sdk-manifests hl2sdk-manifests
          ambuild

      - name: List build directory (Linux)
        run: ls ./build

      - name: Archive build (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: cs2surf-linux
          path: ./build/
