name: Build

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - name: Install OpenSSL 3.0.13
        run: |
          sudo apt update
          sudo apt install -y build-essential checkinstall zlib1g-dev
          wget https://www.openssl.org/source/openssl-3.0.13.tar.gz
          tar -xzf openssl-3.0.13.tar.gz
          cd openssl-3.0.13
          ./config --prefix=/usr/local/openssl-3.0.13 --openssldir=/usr/local/openssl-3.0.13
          make -j$(nproc)
          sudo make install
          echo "/usr/local/openssl-3.0.13/lib" | sudo tee -a /etc/ld.so.conf.d/openssl-3.0.13.conf
          sudo ldconfig
          echo "PATH=/usr/local/openssl-3.0.13/bin:\$PATH" | sudo tee -a /etc/environment
          echo "OPENSSL_ROOT_DIR=/usr/local/openssl-3.0.13" | sudo tee -a /etc/environment
          echo "OPENSSL_LIBRARIES=/usr/local/openssl-3.0.13/lib" | sudo tee -a /etc/environment
          source /etc/environment

      - name: Verify OpenSSL version
        run: openssl version

      - name: Update version header
        run: |
          echo "#define VERSION_STRING \"${{ inputs.version }}\"" > ./src/version.h

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build with CMake
        run: |
          cmake -G Ninja -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="clang-15" -DCMAKE_CXX_COMPILER="clang++-15"
          cmake --build build

      - name: List build directory (Linux)
        run: ls ./build

      - name: Archive build (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: cs2surf-linux
          path: ./build/cs2surf.so
