name: Build

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false

      - name: Update version header
        run: |
          echo "#define VERSION_STRING \"${{ inputs.version }}\"" > ./src/version.h

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build with CMake
        run: |
          cmake -G Ninja -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++"
          cmake --build build

      - name: List build directory (Linux)
        run: ls ./build

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: cs2surf-linux
          path: ./build/cs2surf.so
